In [4]:
import numpy as np
version = np.__version__
print(version)

1.17.0


In [11]:
nd = np.ones([3,4])
print(nd)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
print(np.__version__)

1.17.0


In [8]:
import pandas as pd
pd.__version__

'0.25.0'